env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
rules: { quotes: ['error', 'single', { avoidEscape: true }] }
