env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
rules:
  {
    quotes: ['error', 'single', { avoidEscape: true }],
    no-console: 'off',
    no-restricted-syntax:
      [
        'error',
        {
          'selector': "CallExpression[callee.object.name='console'][callee.property.name!=/^(log|warn|error|info|trace)$/]",
          'message': 'Unexpected property on console object was called',
        },
      ],
  }
